using System.Collections.Generic;

namespace ArcherArcade.Logic.Text
{
    /// <summary>
    /// All UI strings: key → { English, Hinglish }. Placeholders {0}, {1}… must match in both (EditMode test).
    /// Proper nouns (Archer Arcade, archer and enemy names, level names) stay English. The Maa tribute is the same
    /// in both languages.
    /// </summary>
    public static class StringTable
    {
        public static readonly Dictionary<string, string[]> Entries = new Dictionary<string, string[]>
        {
            // ---------- general ----------
            { "app_name", new[] { "Archer Arcade", "Archer Arcade" } },
            { "studio", new[] { "NaveenCodes by Maa Labs™", "NaveenCodes by Maa Labs™" } },
            { "tribute", new[] { "In loving memory of Maa ❤", "In loving memory of Maa ❤" } },
            { "tap_to_start", new[] { "Tap to start", "Shuru karne ke liye tap karo" } },
            { "close", new[] { "Close", "Band karo" } },
            { "ok", new[] { "OK", "Theek hai" } },
            { "cancel", new[] { "Cancel", "Rehne do" } },
            { "collect", new[] { "Collect", "Le lo" } },
            { "continue", new[] { "Continue", "Aage chalo" } },
            { "home", new[] { "Home", "Home" } },
            { "retry", new[] { "Retry", "Phir se" } },
            { "replay", new[] { "Replay", "Dobara khelo" } },
            { "next_level", new[] { "Next level ▶", "Agla level ▶" } },
            { "map", new[] { "Map", "Map" } },
            { "rematch", new[] { "Rematch", "Rematch" } },
            { "coins_n", new[] { "{0} coins", "{0} coins" } },
            { "need_more", new[] { "Need {0} more", "{0} aur chahiye" } },
            { "sec", new[] { "{0}s", "{0}s" } },
            { "meters", new[] { "{0} m", "{0} m" } },
            { "new_badge", new[] { "Badge: {0} · {1}", "Badge: {0} · {1}" } },
            { "tier_bronze", new[] { "Bronze", "Bronze" } },
            { "tier_silver", new[] { "Silver", "Silver" } },
            { "tier_gold", new[] { "Gold", "Gold" } },

            // ---------- home ----------
            { "home_play", new[] { "PLAY", "KHELO" } },
            { "home_campaign", new[] { "Campaign", "Campaign" } },
            { "home_world_level", new[] { "World 1 · Level {0}", "World 1 · Level {0}" } },
            { "home_world_done", new[] { "World 1 cleared! Replay for ★★★", "World 1 poora! ★★★ ke liye dobara khelo" } },
            { "home_archers", new[] { "Archers ▸", "Archers ▸" } },
            { "home_all_modes", new[] { "All modes →", "Saare modes →" } },
            { "home_level", new[] { "Level {0}", "Level {0}" } },
            { "home_lv_ability", new[] { "Lv {0} · {1}", "Lv {0} · {1}" } },
            { "player_default", new[] { "Player", "Player" } },
            { "exit_title", new[] { "Leave Archer Arcade?", "Archer Arcade band karein?" } },
            { "exit_body", new[] { "Your progress is saved on this phone.", "Tumhari progress is phone pe save hai." } },
            { "exit_stay", new[] { "Stay", "Ruko" } },
            { "exit_quit", new[] { "Quit", "Band karo" } },

            // ---------- modes ----------
            { "title_modes", new[] { "Modes", "Modes" } },
            { "mode_campaign", new[] { "Campaign", "Campaign" } },
            { "mode_campaign_sub", new[] { "20 levels · the Forest Warden", "20 levels · Forest Warden boss" } },
            { "mode_quick", new[] { "Quick Duel", "Quick Duel" } },
            { "mode_quick_sub", new[] { "You vs the computer", "Tum vs computer" } },
            { "mode_pvp", new[] { "2 Players", "2 Players" } },
            { "mode_pvp_sub", new[] { "Pass-and-play on one phone", "Ek phone pe baari-baari" } },
            { "mode_daily", new[] { "Daily", "Daily" } },
            { "mode_daily_sub", new[] { "Same level for everyone today", "Aaj sabke liye same level" } },
            { "mode_training", new[] { "Training", "Training" } },
            { "mode_training_sub", new[] { "Practice with the full trajectory", "Poori line ke saath practice" } },
            { "mode_survival", new[] { "Survival", "Survival" } },
            { "mode_survival_sub", new[] { "Endless waves · best: wave {0}", "Lagatar waves · best: wave {0}" } },

            // ---------- map ----------
            { "title_map", new[] { "Campaign", "Campaign" } },
            { "map_stars", new[] { "★ {0} / {1}", "★ {0} / {1}" } },
            { "world_1", new[] { "Forest", "Jungle" } },
            { "world_2", new[] { "Desert", "Registan" } },
            { "world_3", new[] { "Snow Peaks", "Barfeele Pahad" } },
            { "world_4", new[] { "Volcano", "Jwalamukhi" } },
            { "world_5", new[] { "Sky Castle", "Aasmani Kila" } },
            { "map_world_soon_title", new[] { "{0} is on its way", "{0} aa raha hai" } },
            { "map_world_soon_body", new[] { "{0} arrives in a free update. Until then, collect every ★ in the Forest!", "{0} ek free update me aayega. Tab tak Jungle ke saare ★ jeeto!" } },
            { "map_back_forest", new[] { "Back to Forest", "Jungle pe wapas" } },
            { "map_locked_level", new[] { "Clear level {0} first", "Pehle level {0} jeeto" } },
            { "map_progress", new[] { "{0}/20 cleared", "{0}/20 jeete" } },
            { "map_chest_ready", new[] { "Chest ready! Tap to open", "Chest taiyaar! Kholne ke liye tap karo" } },
            { "map_chest_locked", new[] { "Clear level {0} to earn this chest", "Ye chest level {0} jeet kar milega" } },
            { "map_chest_opened", new[] { "Chest opened ✓", "Chest khul gaya ✓" } },

            // ---------- archers ----------
            { "title_archers", new[] { "Archers", "Archers" } },
            { "archers_tap_turn", new[] { "⟲ Tap to turn", "⟲ Ghumane ke liye tap" } },
            { "archers_level", new[] { "Level {0}/{1}", "Level {0}/{1}" } },
            { "stat_hp", new[] { "HP", "HP" } },
            { "stat_damage", new[] { "Damage", "Damage" } },
            { "stat_charge", new[] { "Ability", "Ability" } },
            { "stat_charge_value", new[] { "{0} turns", "{0} turn" } },
            { "archers_passive", new[] { "Passive · ", "Passive · " } },
            { "archers_demo", new[] { "▶ Demo", "▶ Demo" } },
            { "archers_select", new[] { "Select", "Chuno" } },
            { "archers_selected", new[] { "Selected ✓", "Chuna hua ✓" } },
            { "archers_upgrade", new[] { "Upgrade {0}", "Upgrade {0}" } },
            { "archers_max", new[] { "Max level ★", "Max level ★" } },
            { "archers_locked_level", new[] { "Clear level {0} to unlock", "Unlock: level {0} jeeto" } },
            { "archers_locked_stars", new[] { "Earn {0} ★ to unlock ({1}/{0})", "Unlock: {0} ★ jeeto ({1}/{0})" } },
            { "archers_locked_boss", new[] { "Beat the Forest Warden to unlock", "Unlock: Forest Warden ko haraao" } },
            { "archers_need_coins", new[] { "Need {0} more. Earn coins in the campaign, badges and chests.", "{0} aur chahiye. Campaign, badges aur chests se coins kamao." } },
            { "archers_selected_toast", new[] { "{0} selected", "{0} chuna gaya" } },
            { "archers_skin_locked", new[] { "{0}: get it in the Shop", "{0}: Shop me milega" } },
            { "archers_skin_badge", new[] { "{0}: earn the {1} badge ({2})", "{0}: {1} badge jeeto ({2})" } },
            { "el_none", new[] { "Balanced", "Balanced" } },
            { "el_fire", new[] { "Fire", "Aag" } },
            { "el_electric", new[] { "Electric", "Bijli" } },
            { "el_bomb", new[] { "Explosive", "Dhamaka" } },
            { "el_ice", new[] { "Ice", "Barf" } },
            { "el_poison", new[] { "Poison", "Zeher" } },
            { "passive_ranger", new[] { "Steady hand: a 10 % longer aim preview.", "Pakka haath: nishane ki line 10 % lambi." } },
            { "passive_fire", new[] { "Every hit burns for 6 damage on the next 2 turns.", "Har hit jalata hai: agle 2 turn 6-6 damage." } },
            { "passive_electric", new[] { "Hits chain to one more target within 3 m for 50 %.", "Hit 3 m ke andar ek aur target pe 50 % chain hota hai." } },
            { "passive_bomb", new[] { "Arrows explode on impact: +10 splash, crates break.", "Teer takrate hi phat-te hain: +10 splash, crates tootte hain." } },
            { "ability_TripleShot", new[] { "Triple Shot", "Triple Shot" } },
            { "ability_TripleShot_desc", new[] { "Fires 3 arrows in a spread.", "Ek saath 3 teer phailte hue." } },
            { "ability_MeteorArrow", new[] { "Meteor Arrow", "Meteor Arrow" } },
            { "ability_MeteorArrow_desc", new[] { "A flaming arrow: 40 damage + burn, 1.5 m splash.", "Jalta teer: 40 damage + jalan, 1.5 m splash." } },
            { "ability_StormBolt", new[] { "Storm Bolt", "Storm Bolt" } },
            { "ability_StormBolt_desc", new[] { "A fast bolt that ignores the wind: 35 damage, chains twice.", "Tez bijli ka teer, hawa ka asar nahi: 35 damage, do baar chain." } },
            { "ability_ClusterBomb", new[] { "Cluster Bomb", "Cluster Bomb" } },
            { "ability_ClusterBomb_desc", new[] { "Splits into 3 bomblets at the top of its arc.", "Arc ke top pe 3 chhote bomb ban jaata hai." } },
            { "ability_ThornVolley", new[] { "Thorn Volley", "Thorn Volley" } },
            { "ability_RainOfLeaves", new[] { "Rain of Leaves", "Patton ki Baarish" } },
            { "ability_ready", new[] { "{0} ready. Shoot!", "{0} taiyaar. Chalao!" } },
            { "ability_charging", new[] { "{0} charges in {1} more turns", "{0} {1} turn me charge hoga" } },
            { "ability_charging_one", new[] { "{0} charges next turn", "{0} agle turn charge hoga" } },
            { "upgrade_title", new[] { "Upgrade {0}", "{0} upgrade karo" } },
            { "upgrade_level", new[] { "Level {0} → {1}", "Level {0} → {1}" } },
            { "upgrade_stat", new[] { "{0}  {1} → {2}", "{0}  {1} → {2}" } },
            { "upgrade_confirm", new[] { "Upgrade · {0}", "Upgrade · {0}" } },
            { "upgrade_done", new[] { "{0} is now level {1}!", "{0} ab level {1} hai!" } },
            { "unlock_title", new[] { "{0} unlocked!", "{0} unlock ho gaya!" } },
            { "unlock_body", new[] { "A new archer joins your team.", "Team me naya archer aaya." } },
            { "unlock_try", new[] { "Try now", "Abhi try karo" } },
            { "unlock_later", new[] { "Later", "Baad me" } },
            { "tip_unlocked_title", new[] { "New tip: {0}!", "Naya teer: {0}!" } },

            // ---------- loadout ----------
            { "title_loadout", new[] { "Loadout", "Loadout" } },
            { "loadout_sub", new[] { "Get ready", "Taiyaar ho jao" } },
            { "ld_kicker_level", new[] { "{0} · LEVEL {1}", "{0} · LEVEL {1}" } },
            { "ld_kicker_boss", new[] { "{0} · LEVEL {1} · BOSS", "{0} · LEVEL {1} · BOSS" } },
            { "ld_par_turns", new[] { "Par: {0} turns", "Par: {0} turn" } },
            { "ld_par_arrows", new[] { "Par: {0} arrows", "Par: {0} teer" } },
            { "ld_opponent", new[] { "Opponent: {0}", "Saamne: {0}" } },
            { "ld_start", new[] { "START ▶", "SHURU ▶" } },
            { "ld_arrows", new[] { "Arrows", "Teer" } },
            { "ld_arrows_hint", new[] { "pick 3 · limited ammo per match", "3 chuno · har match me limited" } },
            { "ld_normal_always", new[] { "Normal arrows are always in your quiver", "Normal teer hamesha tarkash me rehte hain" } },
            { "ld_max_tips", new[] { "3 arrow types max. Tap one to remove it.", "Max 3 tarah ke teer. Hatane ke liye tap karo." } },
            { "ld_tip_locked", new[] { "{0} unlocks at level {1}", "{0} level {1} pe unlock hoga" } },
            { "ld_tip_lv", new[] { "Lv {0}", "Lv {0}" } },
            { "ld_forced", new[] { "This level gives you: {0}", "Is level me milega: {0}" } },
            { "ld_boosters", new[] { "Boosters", "Boosters" } },
            { "ld_boosters_hint", new[] { "optional · earned coins", "zaroori nahi · kamaye coins" } },
            { "ld_archer", new[] { "Archer", "Archer" } },
            { "ld_skin", new[] { "Skin", "Skin" } },
            { "ld_trail", new[] { "Trail", "Trail" } },
            { "ld_change", new[] { "Change ▸", "Badlo ▸" } },
            { "ld_not_enough", new[] { "Not enough coins for these boosters", "In boosters ke liye coins kam hain" } },
            { "ld_new", new[] { "New!", "Naya!" } },
            { "ld_assist", new[] { "Assist on: +15 % aim preview (max ★★)", "Madad on: nishana line +15 % (max ★★)" } },
            { "ld_assist_offer", new[] { "Tough one? Turn on Assist for this try.", "Mushkil hai? Is baar Madad on karo." } },
            { "ld_best", new[] { "Best", "Best" } },
            { "diff_easy", new[] { "Easy", "Aasaan" } },
            { "diff_medium", new[] { "Medium", "Medium" } },
            { "diff_hard", new[] { "Hard", "Mushkil" } },
            { "qd_kicker", new[] { "QUICK DUEL", "QUICK DUEL" } },
            { "qd_title", new[] { "You vs CPU", "Tum vs CPU" } },
            { "qd_meta", new[] { "Opponent: a random hero · coin flip starts", "Saamne: koi bhi hero · sikka tay karega pehli baari" } },
            { "qd_arena", new[] { "Arena", "Arena" } },
            { "arena_random", new[] { "Random", "Koi bhi" } },
            { "arena_meadow", new[] { "Meadow", "Maidan" } },
            { "arena_fence", new[] { "Fence", "Baad" } },
            { "arena_crates", new[] { "Crates", "Crates" } },
            { "arena_platforms", new[] { "Platforms", "Platforms" } },
            { "arena_barrels", new[] { "Barrels", "Barrels" } },
            { "arena_mirror", new[] { "Mirror Forest", "Mirror Jungle" } },
            { "tr_kicker", new[] { "TRAINING RANGE", "TRAINING RANGE" } },
            { "tr_title", new[] { "Practice", "Practice" } },
            { "tr_goal", new[] { "Hit the board. Full trajectory, no timer.", "Board pe maaro. Poori line, koi timer nahi." } },
            { "tr_distance", new[] { "Distance", "Doori" } },
            { "tr_wind", new[] { "Wind", "Hawa" } },
            { "tr_stats", new[] { "Hits {0}/{1} · Bullseyes {2}", "Hits {0}/{1} · Bullseye {2}" } },
            { "tr_bullseye", new[] { "BULLSEYE!", "BULLSEYE!" } },
            { "daily_kicker", new[] { "DAILY CHALLENGE", "DAILY CHALLENGE" } },

            // ---------- goals ----------
            { "goal_duel", new[] { "Defeat the opponent", "Saamne wale ko haraao" } },
            { "goal_targets", new[] { "Hit {0} targets", "{0} targets pe maaro" } },
            { "goal_apple", new[] { "Hit {0} apples — don't hit the dummy!", "{0} seb giraao — putle ko mat maaro!" } },
            { "goal_gauntlet", new[] { "Beat {0} archers in a row", "{0} archers ko lagatar haraao" } },
            { "goal_rescue", new[] { "Cut the rope to free the fox", "Rassi kaato, lomdi ko bachao" } },
            { "goal_trick", new[] { "Hit {0} hidden targets (bounce!)", "{0} chhupe targets maaro (bounce!)" } },
            { "goal_boss", new[] { "Defeat the Forest Warden", "Forest Warden ko haraao" } },
            { "goal_arrows_left", new[] { "Arrows left: {0}", "Bache teer: {0}" } },
            { "goal_progress", new[] { "{0}/{1}", "{0}/{1}" } },

            // ---------- idea cards ----------
            { "idea_Tutorial", new[] { "Drag back to aim", "Peeche kheecho, nishana lo" } },
            { "idea_Tutorial_text", new[] { "Touch anywhere, drag back, watch the arc, let go to shoot.", "Kahin bhi chhuo, peeche kheecho, line dekho, chhodte hi teer chalega." } },
            { "idea_DuelsAndHp", new[] { "Duels & HP", "Duel aur HP" } },
            { "idea_DuelsAndHp_text", new[] { "Take turns. Every hit takes HP. Knock them out first!", "Baari-baari khelo. Har hit HP ghatata hai. Pehle unhe gira do!" } },
            { "idea_Walls", new[] { "Walls", "Deewar" } },
            { "idea_Walls_text", new[] { "Walls block low shots. Arc over them.", "Deewar neeche wale teer rokti hai. Upar se arc maaro." } },
            { "idea_Wind", new[] { "Wind", "Hawa" } },
            { "idea_Wind_text", new[] { "Wind pushes your arrow. Read the gauge and aim into it.", "Hawa teer ko dhakelti hai. Gauge dekho aur hawa ke ulta nishana lo." } },
            { "idea_Headshots", new[] { "Headshots", "Headshot" } },
            { "idea_Headshots_text", new[] { "A hit on the head deals double damage.", "Sar pe hit = double damage." } },
            { "idea_CrateTowers", new[] { "Crate towers", "Crate tower" } },
            { "idea_CrateTowers_text", new[] { "Knock crates off the tower to open a path.", "Tower se crates giraao, raasta khulega." } },
            { "idea_AppleShot", new[] { "Apple Shot", "Seb ka nishana" } },
            { "idea_AppleShot_text", new[] { "Hit the apple on the dummy's head. Don't hit the dummy!", "Putle ke sar pe rakha seb maaro. Putle ko mat maaro!" } },
            { "idea_SwingingTargets", new[] { "Swinging targets", "Jhoolte targets" } },
            { "idea_SwingingTargets_text", new[] { "Targets swing on ropes. Time your shot.", "Targets rassi pe jhoolte hain. Sahi waqt pe maaro." } },
            { "idea_MovingPlatforms", new[] { "Moving platforms", "Chalte platform" } },
            { "idea_MovingPlatforms_text", new[] { "Platforms move between turns. Aim where they are now.", "Platform har turn ke baad hilte hain. Abhi jahan hain wahan maaro." } },
            { "idea_MiniBoss", new[] { "Mini-boss", "Mini-boss" } },
            { "idea_MiniBoss_text", new[] { "Captain Thorn has more HP and a Thorn Volley. Stay sharp!", "Captain Thorn ke paas zyada HP aur Thorn Volley hai. Dhyaan se!" } },
            { "idea_TntCrates", new[] { "TNT crates", "TNT crate" } },
            { "idea_TntCrates_text", new[] { "Hit a TNT crate and the whole tower goes boom.", "TNT crate maaro, poora tower phatega." } },
            { "idea_ShieldsAndBombs", new[] { "Shields & Bomb tips", "Dhaal aur Bomb teer" } },
            { "idea_ShieldsAndBombs_text", new[] { "Shields block body shots. A Bomb or Heavy tip knocks them down.", "Dhaal body shot rokti hai. Bomb ya Bhaari teer use gira deta hai." } },
            { "idea_BouncePads", new[] { "Bounce pads", "Bounce pad" } },
            { "idea_BouncePads_text", new[] { "Arrows bounce off pads at the mirror angle.", "Teer pad se takra kar ulte angle pe uchhalte hain." } },
            { "idea_Gauntlet", new[] { "Gauntlet", "Gauntlet" } },
            { "idea_Gauntlet_text", new[] { "Beat archers one after another. Your HP carries over.", "Ek ke baad ek archers ko haraao. Tumhara HP aage chalta hai." } },
            { "idea_Rescue", new[] { "Rescue", "Bachao" } },
            { "idea_Rescue_text", new[] { "Cut the rope to free the fox, while an archer shoots at you.", "Rassi kaat kar lomdi ko bachao, jab ek archer tum pe teer chala raha ho." } },
            { "idea_ExplosiveBarrels", new[] { "Explosive barrels", "Dhamaka barrel" } },
            { "idea_ExplosiveBarrels_text", new[] { "Barrels explode when hit. Big boom, big damage.", "Barrel hit hote hi phat-te hain. Bada dhamaka, bada damage." } },
            { "idea_Healers", new[] { "Healers", "Healer" } },
            { "idea_Healers_text", new[] { "The Healer Druid heals every 2 turns. Finish fast!", "Healer Druid har 2 turn me heal karta hai. Jaldi khatam karo!" } },
            { "idea_SplitArrows", new[] { "Split arrows", "Split teer" } },
            { "idea_SplitArrows_text", new[] { "Split tips become 3 arrows at the top of the arc.", "Split teer arc ke top pe 3 teer ban jaate hain." } },
            { "idea_ShieldBubbles", new[] { "Shield bubbles", "Bubble dhaal" } },
            { "idea_ShieldBubbles_text", new[] { "A bubble blocks one hit. Electric tips pop it.", "Bubble ek hit rokta hai. Bijli ka teer use phod deta hai." } },
            { "idea_Boss", new[] { "The Forest Warden", "The Forest Warden" } },
            { "idea_Boss_text", new[] { "Hit the glowing knot on its chest for ×2.5 damage. Shields turn every turn!", "Chhaati ki chamakti gaanth pe maaro: ×2.5 damage. Dhaal har turn ghoomti hai!" } },
            { "idea_TipFire", new[] { "Fire tip", "Aag ka teer" } },
            { "idea_TipFire_text", new[] { "A fireball on impact, then the target burns for 2 turns.", "Takrate hi aag ka gola, phir 2 turn tak jalan." } },
            { "idea_TipElectric", new[] { "Electric tip", "Bijli ka teer" } },
            { "idea_TipElectric_text", new[] { "Lightning strikes from the sky and stuns: −4 s next turn.", "Aasman se bijli girti hai aur stun karti hai: agle turn −4 s." } },
            { "idea_TipSplit", new[] { "Split tip", "Split teer" } },
            { "idea_TipSplit_text", new[] { "Splits into 3 arrows at the top of its arc.", "Arc ke top pe 3 teer ban jaata hai." } },
            { "idea_TipBomb", new[] { "Bomb tip", "Bomb teer" } },
            { "idea_TipBomb_text", new[] { "A big blast: knockback, breaks crates and shields.", "Bada dhamaka: peeche dhakelta hai, crates aur dhaal todta hai." } },
            { "idea_TipHeavy", new[] { "Heavy tip", "Bhaari teer" } },
            { "idea_TipHeavy_text", new[] { "Drops faster, hits harder: +40 % damage. Knocks shields down.", "Jaldi girta hai, zor se lagta hai: +40 % damage. Dhaal gira deta hai." } },
            { "idea_TipIce", new[] { "Ice tip", "Barf ka teer" } },
            { "idea_TipIce_text", new[] { "Freezes the target: its next draw is 30 % slower.", "Target jam jaata hai: agla draw 30 % dheema." } },
            { "idea_TipPoison", new[] { "Poison tip", "Zeher ka teer" } },
            { "idea_TipPoison_text", new[] { "A green cloud poisons for 8 damage on 2 turns.", "Hara badal 2 turn tak 8-8 zeher damage deta hai." } },
            { "idea_got_it", new[] { "Got it!", "Samajh gaya!" } },

            // ---------- tips & boosters ----------
            { "tipname_Normal", new[] { "Normal", "Normal" } },
            { "tipname_Fire", new[] { "Fire", "Aag" } },
            { "tipname_Electric", new[] { "Electric", "Bijli" } },
            { "tipname_Split", new[] { "Split", "Split" } },
            { "tipname_Bomb", new[] { "Bomb", "Bomb" } },
            { "tipname_Heavy", new[] { "Heavy", "Bhaari" } },
            { "tipname_Ice", new[] { "Ice", "Barf" } },
            { "tipname_Poison", new[] { "Poison", "Zeher" } },
            { "tip_no_ammo", new[] { "No {0} arrows left", "{0} teer khatam" } },
            { "booster_ShieldBubble", new[] { "Shield Bubble", "Bubble Dhaal" } },
            { "booster_ShieldBubble_desc", new[] { "Absorbs the first arrow that hits you", "Pehla teer jo tumhe lage, ye rok leta hai" } },
            { "booster_MultiArrow", new[] { "Multi Arrow", "Multi Teer" } },
            { "booster_MultiArrow_desc", new[] { "Your first shot fires 3 arrows", "Pehla shot 3 teer chalata hai" } },
            { "booster_IronHelmet", new[] { "Iron Helmet", "Loha Topi" } },
            { "booster_IronHelmet_desc", new[] { "The first headshot on you counts as a body hit", "Pehla headshot body hit gina jaata hai" } },
            { "booster_ExtraHeart", new[] { "Extra Heart", "Extra Dil" } },
            { "booster_ExtraHeart_desc", new[] { "+25 max HP for this match", "Is match me +25 max HP" } },

            // ---------- loss tips ----------
            { "tip_aim_body", new[] { "Aim for the body first: it's the biggest target.", "Pehle body pe nishana lo: sabse bada target wahi hai." } },
            { "tip_aim_wind", new[] { "Aim into the wind: it pushes your arrow.", "Hawa ke ulta nishana lo: hawa teer ko dhakelti hai." } },
            { "tip_apple_high", new[] { "Aim a little above the apple so you never hit the dummy.", "Seb se thoda upar nishana lo, putla bach jaayega." } },
            { "tip_arc_over", new[] { "Pull back more and aim higher to arc over the wall.", "Zyada kheecho aur upar nishana lo, deewar ke upar se jaayega." } },
            { "tip_blow_tnt", new[] { "Hit the TNT crate: the whole tower blows up.", "TNT crate maaro: poora tower udd jaayega." } },
            { "tip_bomb_shield", new[] { "A Bomb or Heavy tip knocks the shield down for a turn.", "Bomb ya Bhaari teer dhaal ko ek turn ke liye gira deta hai." } },
            { "tip_bounce", new[] { "Bounce off the pad: it sends arrows up at the mirror angle.", "Pad pe takrao: teer ulte angle pe upar jaata hai." } },
            { "tip_cut_rope", new[] { "The rope is thin: aim straight at it, not the cage.", "Rassi patli hai: seedha rassi pe maaro, pinjre pe nahi." } },
            { "tip_drag_back", new[] { "Drag back from anywhere, then let go. Longer drag = stronger shot.", "Kahin se bhi peeche kheecho aur chhodo. Lamba kheecho = tez shot." } },
            { "tip_finish_fast", new[] { "Healers heal every 2 turns: use your strongest arrows early.", "Healer har 2 turn heal karte hain: sabse tez teer pehle chalao." } },
            { "tip_headshot", new[] { "Headshots deal double damage. Aim a little higher.", "Headshot double damage deta hai. Thoda upar nishana lo." } },
            { "tip_knock_crates", new[] { "Knock the top crates off to open a clear path.", "Upar ke crates giraao, raasta saaf ho jaayega." } },
            { "tip_platform_wait", new[] { "Watch where the platform stops, then aim.", "Dekho platform kahan rukta hai, phir nishana lo." } },
            { "tip_pop_bubble", new[] { "An Electric tip pops the bubble shield.", "Bijli ka teer bubble dhaal phod deta hai." } },
            { "tip_save_hp", new[] { "Your HP carries over: play safe early.", "HP aage chalta hai: shuru me sambhal kar khelo." } },
            { "tip_split_cluster", new[] { "Split arrows spread wide: great for clustered targets.", "Split teer phailte hain: paas-paas targets ke liye best." } },
            { "tip_time_swing", new[] { "Shoot when the target swings back towards the middle.", "Jab target beech ki taraf aaye tab chalao." } },
            { "tip_topple_tower", new[] { "Topple the tower under the sniper.", "Sniper ke neeche ka tower giraao." } },
            { "tip_weak_spot", new[] { "Hit the glowing knot when its shield turns away.", "Jab dhaal hate, chamakti gaanth pe maaro." } },

            // ---------- match HUD ----------
            { "hud_you", new[] { "You", "Tum" } },
            { "hud_cpu", new[] { "CPU · {0}", "CPU · {0}" } },
            { "hud_dummy", new[] { "Board", "Board" } },
            { "hud_no_wind", new[] { "No wind", "Hawa nahi" } },
            { "hud_your_turn", new[] { "Your turn · drag back to aim", "Tumhari baari · peeche kheecho" } },
            { "hud_player_turn", new[] { "{0} · drag back to aim", "{0} · peeche kheecho" } },
            { "hud_training", new[] { "Drag back to aim · release to shoot", "Peeche kheecho · chhodo aur chalao" } },
            { "hud_cpu_thinking", new[] { "{0} is thinking…", "{0} soch raha hai…" } },
            { "hud_cpu_aiming", new[] { "{0} is aiming…", "{0} nishana le raha hai…" } },
            { "hud_in_flight", new[] { "Arrow in flight…", "Teer hawa me…" } },
            { "hud_ko", new[] { "K.O.!", "K.O.!" } },
            { "hud_times_up", new[] { "Time's up! Turn passes.", "Time khatam! Baari gayi." } },
            { "hud_headshot", new[] { "HEADSHOT!", "HEADSHOT!" } },
            { "hud_double", new[] { "DOUBLE HIT!", "DOUBLE HIT!" } },
            { "hud_triple", new[] { "TRIPLE HIT!", "TRIPLE HIT!" } },
            { "hud_poof", new[] { "POOF!", "POOF!" } },
            { "hud_blocked", new[] { "BLOCKED!", "ROKA!" } },
            { "hud_miss", new[] { "Miss!", "Chook gaya!" } },
            { "hud_weak_spot", new[] { "WEAK SPOT!", "WEAK SPOT!" } },
            { "hud_heal", new[] { "+{0}", "+{0}" } },
            { "hud_burn", new[] { "BURN!", "JALAN!" } },
            { "hud_stun", new[] { "STUNNED!", "STUN!" } },
            { "hud_frozen", new[] { "FROZEN!", "JAM GAYA!" } },
            { "hud_poison", new[] { "POISONED!", "ZEHER!" } },
            { "hud_bubble", new[] { "BUBBLE!", "BUBBLE!" } },
            { "hud_bubble_pop", new[] { "POP!", "PHAT!" } },
            { "hud_helmet", new[] { "CLANG!", "TANNN!" } },
            { "hud_bullseye", new[] { "BULLSEYE!", "BULLSEYE!" } },
            { "hud_target", new[] { "TARGET!", "TARGET!" } },
            { "hud_apple", new[] { "APPLE!", "SEB!" } },
            { "hud_dummy_hit", new[] { "Oops! The dummy!", "Oops! Putla!" } },
            { "hud_rope", new[] { "FREE!", "AAZAAD!" } },
            { "hud_enraged", new[] { "ENRAGED!", "GUSSA!" } },
            { "hud_vines", new[] { "VINE WALL!", "BEL KI DEEWAR!" } },
            { "hud_next_archer", new[] { "Next: {0}", "Agla: {0}" } },
            { "hud_coin_flip", new[] { "{0} goes first!", "Pehli baari: {0}!" } },
            { "hud_power", new[] { "{0}%", "{0}%" } },
            { "hud_hits", new[] { "Hits {0}", "Hits {0}" } },
            { "hud_headshots", new[] { "Heads {0}", "Heads {0}" } },
            { "hud_wave", new[] { "Wave {0}", "Wave {0}" } },
            { "hud_round", new[] { "Round {0} · {1}–{2}", "Round {0} · {1}–{2}" } },

            // ---------- pause ----------
            { "pause_title", new[] { "Paused", "Ruka hua" } },
            { "pause_resume", new[] { "Resume", "Chalu karo" } },
            { "pause_restart", new[] { "Restart", "Phir se" } },
            { "pause_quit", new[] { "Quit", "Chhodo" } },
            { "pause_sound_on", new[] { "Sound on", "Awaaz on" } },
            { "pause_sound_off", new[] { "Sound off", "Awaaz off" } },
            { "pause_settings", new[] { "Settings", "Settings" } },

            // ---------- 2-player ----------
            { "title_pvp", new[] { "2 Players", "2 Players" } },
            { "pvp_player", new[] { "Player {0}", "Player {0}" } },
            { "pvp_name", new[] { "Name", "Naam" } },
            { "pvp_handicap", new[] { "HP ×{0}", "HP ×{0}" } },
            { "pvp_best_of", new[] { "Best of", "Best of" } },
            { "pvp_wind", new[] { "Wind", "Hawa" } },
            { "pvp_preview", new[] { "Aim preview {0}%", "Nishana line {0}%" } },
            { "pvp_arena", new[] { "Arena", "Arena" } },
            { "pvp_start", new[] { "START DUEL ▶", "DUEL SHURU ▶" } },
            { "pass_title", new[] { "Pass the phone", "Phone aage do" } },
            { "pass_turn", new[] { "{0}, your turn", "{0}, tumhari baari" } },
            { "pass_hidden", new[] { "The last aim is hidden. No peeking.", "Pichla nishana chhupa hai. Jhaankna mana hai." } },
            { "pass_ready", new[] { "I'm ready", "Main taiyaar hoon" } },
            { "pvp_round_win", new[] { "{0} wins round {1}!", "{0} ne round {1} jeeta!" } },
            { "pvp_series_win", new[] { "{0} wins!", "{0} jeet gaya!" } },
            { "pvp_score", new[] { "{0}  {1} – {2}  {3}", "{0}  {1} – {2}  {3}" } },
            { "pvp_next_round", new[] { "Next round ▶", "Agla round ▶" } },
            { "pvp_swap", new[] { "Swap sides", "Side badlo" } },
            { "pvp_great", new[] { "Great duel. Rematch?", "Zabardast duel. Rematch?" } },

            // ---------- results ----------
            { "res_victory", new[] { "VICTORY!", "JEET GAYE!" } },
            { "res_cleared", new[] { "Level cleared", "Level poora" } },
            { "res_duel_won", new[] { "Duel won", "Duel jeeta" } },
            { "res_daily_done", new[] { "Today's challenge solved!", "Aaj ka challenge poora!" } },
            { "res_defeat", new[] { "So close!", "Bas thoda sa!" } },
            { "res_defeat_sub", new[] { "The opponent won this round", "Is baar saamne wala jeeta" } },
            { "res_failed_sub", new[] { "Out of arrows. Try a new plan!", "Teer khatam. Naya plan try karo!" } },
            { "res_dummy_sub", new[] { "The dummy got hit. Aim above it!", "Putle ko lag gaya. Upar nishana lo!" } },
            { "res_headshots", new[] { "Headshots", "Headshots" } },
            { "res_arrows", new[] { "Arrows used", "Teer lage" } },
            { "res_hp", new[] { "HP left", "HP bacha" } },
            { "res_turns", new[] { "Turns", "Turns" } },
            { "res_tip", new[] { "Tip: {0}", "Tip: {0}" } },
            { "res_first_clear", new[] { "First clear +{0}", "Pehli jeet +{0}" } },
            { "res_chest_ready", new[] { "A chest is ready!", "Ek chest taiyaar hai!" } },
            { "res_open_chest", new[] { "Open chest", "Chest kholo" } },
            { "res_streak", new[] { "Streak: {0} days", "Streak: {0} din" } },
            { "res_new_best", new[] { "New best!", "Naya best!" } },
            { "res_assist", new[] { "Assist", "Madad" } },

            // ---------- chests ----------
            { "title_chests", new[] { "Chests", "Chests" } },
            { "chest_1", new[] { "Wooden Chest", "Lakdi ka Chest" } },
            { "chest_2", new[] { "Silver Chest", "Chaandi ka Chest" } },
            { "chest_3", new[] { "Gold Chest", "Sone ka Chest" } },
            { "chest_4", new[] { "Forest Chest", "Jungle Chest" } },
            { "chest_contents", new[] { "{0}–{1} coins · maybe a skin or trail", "{0}–{1} coins · shayad skin ya trail" } },
            { "chest_open", new[] { "Open", "Kholo" } },
            { "chest_opened", new[] { "Opened ✓", "Khul gaya ✓" } },
            { "chest_clear", new[] { "Clear level {0}", "Level {0} jeeto" } },
            { "chest_note", new[] { "Chest contents are earned by playing. Nothing is ever for sale.", "Chest ka saaman khel kar milta hai. Kuch bhi bikta nahi." } },
            { "chest_opened_title", new[] { "{0} opened!", "{0} khul gaya!" } },
            { "chest_tap", new[] { "Tap the chest!", "Chest pe tap karo!" } },

            // ---------- shop ----------
            { "title_shop", new[] { "Shop", "Shop" } },
            { "shop_note", new[] { "Coins only. Every coin is earned by playing. No real money, ever.", "Sirf coins. Har coin khel kar kamaya. Asli paisa kabhi nahi." } },
            { "shop_skin", new[] { "Skin · {0}", "Skin · {0}" } },
            { "shop_trail", new[] { "Arrow trail", "Teer ki trail" } },
            { "shop_owned", new[] { "Owned ✓", "Tumhara ✓" } },
            { "shop_equip", new[] { "Equip", "Pehno" } },
            { "shop_equipped", new[] { "Equipped ✓", "Pehna hua ✓" } },
            { "shop_badge", new[] { "Badge reward", "Badge inaam" } },
            { "shop_streak", new[] { "7-day streak", "7 din ki streak" } },
            { "shop_bought", new[] { "{0} is yours!", "{0} ab tumhara!" } },
            { "shop_buy", new[] { "Buy · {0}", "Lo · {0}" } },
            { "shop_preview", new[] { "Preview", "Dekho" } },
            { "shop_needs_archer", new[] { "Unlock {0} first", "Pehle {0} unlock karo" } },
            { "cos_skin_ranger_default", new[] { "Ranger Green", "Ranger Green" } },
            { "cos_skin_ranger_forest", new[] { "Forest Cloak", "Forest Cloak" } },
            { "cos_skin_fire_default", new[] { "Flame Red", "Flame Red" } },
            { "cos_skin_fire_ember", new[] { "Ember Coat", "Ember Coat" } },
            { "cos_skin_electric_default", new[] { "Volt Yellow", "Volt Yellow" } },
            { "cos_skin_electric_neon", new[] { "Neon Bolt", "Neon Bolt" } },
            { "cos_skin_bomb_default", new[] { "Blast Orange", "Blast Orange" } },
            { "cos_skin_bomb_goggles", new[] { "Blast Goggles", "Blast Goggles" } },
            { "cos_trail_classic", new[] { "Classic", "Classic" } },
            { "cos_trail_sparkle", new[] { "Sparkle", "Sparkle" } },
            { "cos_trail_rainbow", new[] { "Rainbow", "Rainbow" } },
            { "cos_trail_comet", new[] { "Comet", "Comet" } },

            // ---------- badges ----------
            { "title_badges", new[] { "Badges", "Badges" } },
            { "badges_pinned", new[] { "Pinned", "Pinned" } },
            { "badges_pinned_help", new[] { "Shown on your profile. Tap an earned badge to pin or unpin it.", "Profile pe dikhte hain. Jeeta hua badge tap karke pin/unpin karo." } },
            { "badges_earned", new[] { " earned", " jeete" } },
            { "badges_max_pins", new[] { "3 pins max. Unpin one first.", "Max 3 pin. Pehle ek hatao." } },
            { "badges_pin", new[] { "Pin to profile", "Profile pe pin karo" } },
            { "badges_unpin", new[] { "Unpin", "Unpin" } },
            { "badges_locked", new[] { "Not earned yet", "Abhi nahi jeeta" } },
            { "badges_next", new[] { "Next: {0} at {1}", "Agla: {0} pe {1}" } },
            { "badges_none_pinned", new[] { "Earn a badge, then pin it here.", "Badge jeeto, phir yahan pin karo." } },
            { "badge_unlocked", new[] { "Badge unlocked: {0}!", "Badge mila: {0}!" } },


            // ---------- badge descriptions (names stay English) ----------
            { "badge_sharpshooter_desc", new[] { "Headshots", "Headshots" } },
            { "badge_bullseye_desc", new[] { "Target-level hits", "Target levels me hits" } },
            { "badge_untouchable_desc", new[] { "Wins without taking damage", "Bina damage khaaye jeet" } },
            { "badge_wind_whisperer_desc", new[] { "Hits in wind 4 or more", "Hawa 4+ me hits" } },
            { "badge_long_shot_desc", new[] { "Hits from 35 m or more", "35 m ya zyada se hits" } },
            { "badge_firestarter_desc", new[] { "Burn damage dealt", "Jalan se diya damage" } },
            { "badge_chain_reaction_desc", new[] { "Electric chains", "Bijli ki chains" } },
            { "badge_demolition_desc", new[] { "Crates and barrels destroyed", "Crates aur barrel tode" } },
            { "badge_triple_threat_desc", new[] { "Triple Shot hits", "Triple Shot hits" } },
            { "badge_forest_hero_desc", new[] { "World 1 stars", "World 1 ke stars" } },
            { "badge_warden_slayer_desc", new[] { "Beat the Forest Warden", "Forest Warden ko haraao" } },
            { "badge_quick_draw_desc", new[] { "Shots released in under 3 s", "3 s se pehle chalaye teer" } },
            { "badge_comeback_desc", new[] { "Wins with under 15 % HP", "15 % se kam HP me jeet" } },
            { "badge_duelist_desc", new[] { "2-Player matches played", "2-Player match khele" } },
            { "badge_friendly_rivals_desc", new[] { "2-Player best-of-3 finished", "2-Player best-of-3 poore" } },
            { "badge_daily_devotee_desc", new[] { "Daily streak", "Daily streak" } },
            { "badge_collector_desc", new[] { "Archers owned", "Archers mile" } },
            { "badge_upgrader_desc", new[] { "Total archer levels", "Archers ke kul levels" } },
            { "badge_apple_picker_desc", new[] { "Apples hit", "Seb giraaye" } },
            { "badge_coin_keeper_desc", new[] { "Coins earned in total", "Kul coins kamaaye" } },
            { "badge_thunderstruck_desc", new[] { "Lightning strikes landed", "Bijli ke waar" } },
            { "badge_tower_toppler_desc", new[] { "Crate towers knocked down", "Crate tower giraaye" } },

            // ---------- daily ----------
            { "title_daily", new[] { "Daily Challenge", "Daily Challenge" } },
            { "daily_seed", new[] { "{0} · SEED #{1}", "{0} · SEED #{1}" } },
            { "daily_same", new[] { "Same level for every player today. Works offline.", "Aaj har player ke liye same level. Bina internet chalta hai." } },
            { "daily_play", new[] { "Play today's level", "Aaj ka level khelo" } },
            { "daily_solved", new[] { "Solved ✓ · back tomorrow", "Ho gaya ✓ · kal milte hain" } },
            { "daily_streak", new[] { "{0}-day streak", "{0} din ki streak" } },
            { "daily_best", new[] { "Best {0}", "Best {0}" } },
            { "daily_note", new[] { "Day 7 reward: 300 coins + Rainbow trail. Missing a day resets the streak. There is no way to pay to restore it.", "Day 7 inaam: 300 coins + Rainbow trail. Ek din chhoota to streak reset. Paise se wapas nahi hoti." } },
            { "daily_reward", new[] { "Reward: {0} coins", "Inaam: {0} coins" } },
            { "tpl_Duel", new[] { "Windy Canyon Duel", "Hawadar Ghaati Duel" } },
            { "tpl_Targets", new[] { "Target Rush", "Target Rush" } },
            { "tpl_Apple", new[] { "Apple Orchard", "Seb ka Baag" } },
            { "tpl_Trick", new[] { "Bounce House", "Bounce House" } },
            { "twist_StrongWind", new[] { "Strong wind", "Tez hawa" } },
            { "twist_SplitOnly", new[] { "Split arrows only", "Sirf Split teer" } },
            { "twist_HeavyOnly", new[] { "Heavy arrows only", "Sirf Bhaari teer" } },
            { "twist_LongDuel", new[] { "One arrow per turn at 35 m", "35 m se ek teer har turn" } },
            { "twist_TinyTargets", new[] { "Tiny targets", "Chhote targets" } },
            { "twist_Night", new[] { "Night + fireflies", "Raat + jugnu" } },
            { "day_mon", new[] { "Mon", "Som" } },
            { "day_tue", new[] { "Tue", "Mangal" } },
            { "day_wed", new[] { "Wed", "Budh" } },
            { "day_thu", new[] { "Thu", "Guru" } },
            { "day_fri", new[] { "Fri", "Shukr" } },
            { "day_sat", new[] { "Sat", "Shani" } },
            { "day_sun", new[] { "Sun", "Ravi" } },

            // ---------- stats ----------
            { "title_stats", new[] { "Stats", "Stats" } },
            { "st_accuracy", new[] { "Accuracy", "Accuracy" } },
            { "st_headshots", new[] { "Headshots", "Headshots" } },
            { "st_won", new[] { "Matches won", "Match jeete" } },
            { "st_winrate", new[] { "Win rate", "Jeet ka %" } },
            { "st_longest", new[] { "Longest shot", "Sabse lamba shot" } },
            { "st_favourite", new[] { "Favourite archer", "Pasandida archer" } },
            { "st_streak", new[] { "Best daily streak", "Best daily streak" } },
            { "st_time", new[] { "Time played", "Khela gaya time" } },
            { "st_shots", new[] { "Shots fired", "Teer chalaye" } },
            { "st_targets", new[] { "Targets hit", "Targets lage" } },
            { "st_quick", new[] { "Quick Duel W–L", "Quick Duel W–L" } },
            { "st_pvp", new[] { "2-Player matches", "2-Player match" } },
            { "st_stars", new[] { "Stars", "Stars" } },
            { "st_days", new[] { "{0} days", "{0} din" } },
            { "st_hm", new[] { "{0}h {1}m", "{0}h {1}m" } },
            { "st_m", new[] { "{0}m", "{0}m" } },

            // ---------- settings ----------
            { "title_settings", new[] { "Settings", "Settings" } },
            { "set_sound", new[] { "Sound", "Awaaz" } },
            { "set_music", new[] { "Music · {0}", "Music · {0}" } },
            { "set_sfx", new[] { "Sound effects · {0}", "Sound effects · {0}" } },
            { "set_haptics", new[] { "Haptics", "Vibration" } },
            { "set_haptics_desc", new[] { "Buzz on draw, release and hits", "Kheechne, chhodne aur hit pe buzz" } },
            { "set_sensitivity", new[] { "Aim sensitivity · {0}", "Nishana sensitivity · {0}" } },
            { "set_display", new[] { "Display", "Display" } },
            { "set_theme_auto", new[] { "Auto", "Auto" } },
            { "set_theme_light", new[] { "Light", "Light" } },
            { "set_theme_dark", new[] { "Dark", "Dark" } },
            { "set_battery", new[] { "Battery saver", "Battery saver" } },
            { "set_battery_desc", new[] { "Cap at 60 fps", "60 fps tak" } },
            { "set_colorblind", new[] { "Colour-blind mode", "Colour-blind mode" } },
            { "set_colorblind_desc", new[] { "Blue/orange HP bars, icons on everything", "Neela/orange HP bar, har cheez pe icon" } },
            { "set_reduce_motion", new[] { "Reduce motion", "Kam hilna-dulna" } },
            { "set_reduce_motion_desc", new[] { "Less shake, no slow-mo", "Kam shake, slow-mo nahi" } },
            { "set_language", new[] { "Language", "Bhasha" } },
            { "set_lang_en", new[] { "English", "English" } },
            { "set_lang_hi", new[] { "Hinglish", "Hinglish" } },
            { "set_controls", new[] { "Controls & access", "Controls aur access" } },
            { "set_left", new[] { "Left-handed", "Left-handed" } },
            { "set_left_desc", new[] { "Mirror the match controls", "Match ke buttons ulte" } },
            { "set_big", new[] { "Bigger touch targets", "Bade buttons" } },
            { "set_big_desc", new[] { "Larger HUD buttons", "HUD ke bade buttons" } },
            { "set_assist", new[] { "Trajectory assist", "Line assist" } },
            { "set_assist_desc", new[] { "Longer aim preview (Easy levels, Training, 2-Player)", "Lambi nishana line (Easy levels, Training, 2-Player)" } },
            { "set_how_to", new[] { "How to play", "Kaise khelein" } },
            { "set_credits", new[] { "Credits", "Credits" } },
            { "set_privacy", new[] { "Privacy", "Privacy" } },
            { "set_name", new[] { "Your name", "Tumhara naam" } },

            // ---------- how to play, privacy, credits ----------
            { "title_how_to", new[] { "How to play", "Kaise khelein" } },
            { "how_to_sub", new[] { "Tap a card to see it again", "Card tap karke dobara dekho" } },
            { "title_privacy", new[] { "Privacy", "Privacy" } },
            { "privacy_body", new[] { "Archer Arcade works fully offline. It has no ads, no accounts, no analytics and no internet permission. Your progress is saved only on this phone. Uninstalling the game deletes it.", "Archer Arcade poori tarah offline chalta hai. Koi ads, account, analytics ya internet permission nahi. Tumhari progress sirf is phone pe save hoti hai. Game hatane se wo bhi hat jaati hai." } },
            { "title_credits", new[] { "Credits", "Credits" } },
            { "credits_by", new[] { "A game by NaveenCodes by Maa Labs™", "NaveenCodes by Maa Labs™ ka game" } },
            { "credits_dev", new[] { "Design & development · Naveen Goyal", "Design aur development · Naveen Goyal" } },
            { "credits_free", new[] { "Free forever · No ads · No purchases · No tracking · Saved on your phone", "Hamesha free · Koi ads nahi · Koi kharidari nahi · Koi tracking nahi · Phone pe save" } },
            { "credits_licences", new[] { "Fonts: Fredoka and Nunito (SIL Open Font License) · Icons: Material Symbols (Apache 2.0) · Made with Unity", "Fonts: Fredoka aur Nunito (SIL Open Font License) · Icons: Material Symbols (Apache 2.0) · Unity se bana" } },

            // ---------- coins ----------
            { "coins_title", new[] { "Your coins", "Tumhare coins" } },
            { "coins_where", new[] { "Coins are only earned by playing:", "Coins sirf khel kar milte hain:" } },
            { "coins_src_campaign", new[] { "Clear campaign levels and earn stars", "Campaign levels jeeto aur stars lo" } },
            { "coins_src_headshots", new[] { "Land headshots", "Headshot maaro" } },
            { "coins_src_badges", new[] { "Earn badge tiers", "Badge tiers jeeto" } },
            { "coins_src_chests", new[] { "Open chests", "Chests kholo" } },
            { "coins_src_daily", new[] { "Solve the Daily Challenge", "Daily Challenge poora karo" } },
            { "coins_src_quick", new[] { "Win Quick Duels", "Quick Duel jeeto" } },
            { "coins_no_buy", new[] { "There is no way to buy coins. Ever.", "Coins khareedne ka koi tareeka nahi. Kabhi nahi." } },
            { "coins_missing_title", new[] { "Not enough coins", "Coins kam hain" } },
            { "coins_missing_body", new[] { "You need {0} more. Here's how to earn them:", "{0} aur chahiye. Aise kamao:" } },

            // ---------- tutorial ----------
            { "tut_drag", new[] { "Drag back from anywhere to aim", "Kahin se bhi peeche kheecho" } },
            { "tut_release", new[] { "Let go to shoot!", "Chhodo aur chalao!" } },
            { "tut_power", new[] { "Longer drag = stronger shot", "Lamba kheecho = tez shot" } },
            { "tut_nice", new[] { "Nice shot!", "Badhiya shot!" } },
            { "tut_skip", new[] { "Skip", "Skip" } },
            { "tut_hit_all", new[] { "Hit all 3 targets", "Teeno targets maaro" } },

            // ---------- survival ----------
            { "sv_kicker", new[] { "SURVIVAL", "SURVIVAL" } },
            { "sv_title", new[] { "Endless waves", "Lagatar waves" } },
            { "sv_goal", new[] { "Beat as many archers as you can. HP carries over, +20 between waves.", "Jitne ho sake utne archers haraao. HP aage chalta hai, har wave ke beech +20." } },
            { "sv_best", new[] { "Best: wave {0}", "Best: wave {0}" } },
            { "sv_run_over", new[] { "Run over", "Khel khatam" } },
            { "sv_reached", new[] { "You reached wave {0}", "Tum wave {0} tak pahunche" } },
            { "sv_wave_clear", new[] { "Wave {0} cleared!", "Wave {0} poori!" } },
        };
    }
}
