namespace ArcherArcade.Core
{
    /// <summary>The three scenes (CLAUDE.md), generated by the Build ▸ Scenes builder.</summary>
    public static class SceneNames
    {
        public const string Boot = "Boot";
        public const string Home = "Home";
        public const string Match = "Match";
    }
}
