// <auto-generated> by Tools/build_fonts.py — do not edit; add icons to ICONS there and re-run.
using System.Collections.Generic;

namespace ArcherArcade.UI
{
    /// <summary>Material Symbols Rounded glyphs used by the game (font: Resources/Fonts/Icons-Rounded).</summary>
    public static class Icons
    {
        public const string AcUnit = "\ueb3b";
        public const string Add = "\ue145";
        public const string Adjust = "\ue39e";
        public const string Air = "\uefd8";
        public const string ArrowBack = "\ue5c4";
        public const string ArrowForward = "\ue5c8";
        public const string ArrowRightAlt = "\ue941";
        public const string ArrowUpward = "\ue5d8";
        public const string AutoAwesome = "\ue65f";
        public const string BackHand = "\ue764";
        public const string BarChart = "\ue26b";
        public const string BatterySaver = "\uefde";
        public const string Bedtime = "\uf159";
        public const string Bolt = "\uea0b";
        public const string Bomb = "\uf568";
        public const string Brush = "\ue3ae";
        public const string BubbleChart = "\ue6dd";
        public const string Cached = "\ue86a";
        public const string CalendarMonth = "\uebcc";
        public const string CallSplit = "\ue0b6";
        public const string CardGiftcard = "\ue8f6";
        public const string Celebration = "\uea65";
        public const string Check = "\ue668";
        public const string CheckCircle = "\uf0be";
        public const string Checkroom = "\uf19e";
        public const string ChevronLeft = "\ue5cb";
        public const string ChevronRight = "\ue5cc";
        public const string Close = "\ue5cd";
        public const string Contrast = "\ueb37";
        public const string Crown = "\uecb3";
        public const string DarkMode = "\ue51c";
        public const string Diamond = "\uead5";
        public const string DomainDisabled = "\ue0ef";
        public const string DoneAll = "\ue877";
        public const string Edit = "\uf097";
        public const string ElectricBolt = "\uec1c";
        public const string EmojiEvents = "\uea23";
        public const string ExitToApp = "\ue879";
        public const string ExpandMore = "\ue5cf";
        public const string Explosion = "\uf685";
        public const string Favorite = "\ue87e";
        public const string FitnessCenter = "\ueb43";
        public const string Flag = "\uf0c6";
        public const string Forest = "\uea99";
        public const string Gesture = "\ue155";
        public const string Group = "\uea21";
        public const string Groups = "\uf233";
        public const string Handshake = "\uebcb";
        public const string Healing = "\ue3f3";
        public const string HealthAndSafety = "\ue1d5";
        public const string Help = "\ue8fd";
        public const string Home = "\ue9b2";
        public const string HourglassEmpty = "\ue88b";
        public const string Info = "\ue88e";
        public const string Inventory2 = "\ue1a1";
        public const string LightMode = "\ue518";
        public const string LocalFireDepartment = "\uef55";
        public const string Lock = "\ue899";
        public const string LockOpen = "\ue898";
        public const string Logout = "\ue9ba";
        public const string Map = "\ue55b";
        public const string MilitaryTech = "\uea3f";
        public const string MonetizationOn = "\ue263";
        public const string MotionPhotosOff = "\ue9c0";
        public const string MusicNote = "\ue405";
        public const string Nightlight = "\uf03d";
        public const string Nutrition = "\ue110";
        public const string Palette = "\ue40a";
        public const string Pause = "\ue034";
        public const string Person = "\uf0d3";
        public const string PlayArrow = "\ue037";
        public const string PrivacyTip = "\uf0dc";
        public const string Psychology = "\uea4a";
        public const string Redeem = "\ue8f6";
        public const string Remove = "\ue15b";
        public const string Replay = "\ue042";
        public const string RocketLaunch = "\ueb9b";
        public const string Savings = "\ue2eb";
        public const string Science = "\uea4b";
        public const string Settings = "\ue8b8";
        public const string Shield = "\ue9e0";
        public const string Shuffle = "\ue043";
        public const string Skull = "\uf89a";
        public const string Speed = "\ue9e4";
        public const string SportsScore = "\uf06e";
        public const string Star = "\uf09a";
        public const string Storefront = "\uea12";
        public const string Straighten = "\ue41c";
        public const string SwapHoriz = "\ue8d4";
        public const string Swords = "\uf889";
        public const string Target = "\ue719";
        public const string Thunderstorm = "\uebdb";
        public const string Timer = "\ue425";
        public const string TouchApp = "\ue913";
        public const string TrackChanges = "\ue8e1";
        public const string Translate = "\ue8e2";
        public const string TrendingUp = "\ue8e5";
        public const string Tune = "\ue429";
        public const string Upgrade = "\uf0fb";
        public const string Vibration = "\uf2cb";
        public const string Visibility = "\ue8f4";
        public const string VolumeOff = "\ue04f";
        public const string VolumeUp = "\ue050";
        public const string WaterDrop = "\ue798";
        public const string WbSunny = "\ue430";
        public const string WbTwilight = "\ue1c6";
        public const string Weight = "\ue13d";
        public const string WorkspacePremium = "\ue7af";
        public const string ZoomIn = "\ue8ff";

        static readonly Dictionary<string, string> ByNameMap = new Dictionary<string, string>
        {
            { "ac_unit", AcUnit },
            { "add", Add },
            { "adjust", Adjust },
            { "air", Air },
            { "arrow_back", ArrowBack },
            { "arrow_forward", ArrowForward },
            { "arrow_right_alt", ArrowRightAlt },
            { "arrow_upward", ArrowUpward },
            { "auto_awesome", AutoAwesome },
            { "back_hand", BackHand },
            { "bar_chart", BarChart },
            { "battery_saver", BatterySaver },
            { "bedtime", Bedtime },
            { "bolt", Bolt },
            { "bomb", Bomb },
            { "brush", Brush },
            { "bubble_chart", BubbleChart },
            { "cached", Cached },
            { "calendar_month", CalendarMonth },
            { "call_split", CallSplit },
            { "card_giftcard", CardGiftcard },
            { "celebration", Celebration },
            { "check", Check },
            { "check_circle", CheckCircle },
            { "checkroom", Checkroom },
            { "chevron_left", ChevronLeft },
            { "chevron_right", ChevronRight },
            { "close", Close },
            { "contrast", Contrast },
            { "crown", Crown },
            { "dark_mode", DarkMode },
            { "diamond", Diamond },
            { "domain_disabled", DomainDisabled },
            { "done_all", DoneAll },
            { "edit", Edit },
            { "electric_bolt", ElectricBolt },
            { "emoji_events", EmojiEvents },
            { "exit_to_app", ExitToApp },
            { "expand_more", ExpandMore },
            { "explosion", Explosion },
            { "favorite", Favorite },
            { "fitness_center", FitnessCenter },
            { "flag", Flag },
            { "forest", Forest },
            { "gesture", Gesture },
            { "group", Group },
            { "groups", Groups },
            { "handshake", Handshake },
            { "healing", Healing },
            { "health_and_safety", HealthAndSafety },
            { "help", Help },
            { "home", Home },
            { "hourglass_empty", HourglassEmpty },
            { "info", Info },
            { "inventory_2", Inventory2 },
            { "light_mode", LightMode },
            { "local_fire_department", LocalFireDepartment },
            { "lock", Lock },
            { "lock_open", LockOpen },
            { "logout", Logout },
            { "map", Map },
            { "military_tech", MilitaryTech },
            { "monetization_on", MonetizationOn },
            { "motion_photos_off", MotionPhotosOff },
            { "music_note", MusicNote },
            { "nightlight", Nightlight },
            { "nutrition", Nutrition },
            { "palette", Palette },
            { "pause", Pause },
            { "person", Person },
            { "play_arrow", PlayArrow },
            { "privacy_tip", PrivacyTip },
            { "psychology", Psychology },
            { "redeem", Redeem },
            { "remove", Remove },
            { "replay", Replay },
            { "rocket_launch", RocketLaunch },
            { "savings", Savings },
            { "science", Science },
            { "settings", Settings },
            { "shield", Shield },
            { "shuffle", Shuffle },
            { "skull", Skull },
            { "speed", Speed },
            { "sports_score", SportsScore },
            { "star", Star },
            { "storefront", Storefront },
            { "straighten", Straighten },
            { "swap_horiz", SwapHoriz },
            { "swords", Swords },
            { "target", Target },
            { "thunderstorm", Thunderstorm },
            { "timer", Timer },
            { "touch_app", TouchApp },
            { "track_changes", TrackChanges },
            { "translate", Translate },
            { "trending_up", TrendingUp },
            { "tune", Tune },
            { "upgrade", Upgrade },
            { "vibration", Vibration },
            { "visibility", Visibility },
            { "volume_off", VolumeOff },
            { "volume_up", VolumeUp },
            { "water_drop", WaterDrop },
            { "wb_sunny", WbSunny },
            { "wb_twilight", WbTwilight },
            { "weight", Weight },
            { "workspace_premium", WorkspacePremium },
            { "zoom_in", ZoomIn },
        };

        /// <summary>Glyph for a Material Symbols name (e.g. from badge data); a star if unknown.</summary>
        public static string ByName(string name) => name != null && ByNameMap.TryGetValue(name, out string g) ? g : Star;
    }
}
